apiVersion: apps/v1
kind: Deployment
metadata:
  name: normalized-deployment-name
  labels:
    app: normalized-deployment-name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: normalized-deployment-name
  template:
    metadata:
      labels:
        app: normalized-deployment-name
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '8080'
        prometheus.io/normalizer: 'true'
    spec:
      containers:
      - name: my-normalized
        image: eu.gcr.io/cool-wharf-207907/kaiko-normalized:0.0.9
        imagePullPolicy: Always
        env:
        - name: SUB_NAME 
          value: "SUB_NAME_TPL"
        - name: TOPIC_NAME 
          value: "projects/cool-wharf-207907/topics/normalized_topic"
        resources:
          requests:
            memory: 20M
            cpu: 10m
          limits:
            memory: 20M
            cpu: 10m
        volumeMounts:
          - name: secret-sa
            mountPath: "/secret"
            readOnly: true
      terminationGracePeriodSeconds: 15
      volumes:
      - name: secret-sa
        secret:
          secretName: sa-gcp-pubsub
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: normalized-hpa-name
spec:
  minReplicas: 10
  maxReplicas: 3000
  metrics:
  - external:
      metricName: pubsub.googleapis.com|subscription|num_undelivered_messages
      metricSelector:
        matchLabels:
          resource.labels.subscription_id: SUB_SHORT_NAME_TPL
      targetAverageValue: "100"
    type: External
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: normalized-deployment-name
