apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-conf
  namespace: kube-system
data:
  traefik.toml: |
    # traefik.toml
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
        address = ":80"
      [entryPoints.ping]
        address = ":8082"
    [metrics]
      [metrics.prometheus]
        entryPoint = "ping"
    [ping]
      entryPoint = "ping"
    [consul]
      endpoint = "traefik-consul:8500"
      watch = true
      prefix = "traefik"
    [kubernetes]
      labelselector = "traffic-type=external"