apiVersion: v1
kind: Service
metadata:
  name: traefik-admin-ingress-service
  namespace: kube-system
  labels:
    k8s-app: traefik-admin-ingress-lb
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
    external-dns.alpha.kubernetes.io/hostname: public.gcp.wescale
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  # loadBalancerSourceRanges: {}
  selector:
    k8s-app: traefik-admin-ingress-lb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: web
    - protocol: TCP
      port: 8080
      name: admin
    - protocol: TCP
      port: 443
      name: web-secure
    - protocol: TCP
      port: 8082
      name: metrics
    