---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-admin-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-admin-ingress-lb
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: traefik-admin-ingress-lb
      name: traefik-admin-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-admin-ingress-lb
        name: traefik-admin-ingress-lb
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8082'
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: k8s-app
                  operator: In
                  values:
                  - traefik-admin-ingress-lb
              topologyKey: "kubernetes.io/hostname"
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - traefik-consul
              topologyKey: "kubernetes.io/hostname"
      serviceAccountName: traefik-admin-ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik:1.7
        name: traefik-admin-ingress-lb
        ports:
        - name: http
          containerPort: 80
        - name: admin
          containerPort: 8080
        - name: metrics
          containerPort: 8082
        securityContext:
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
        args:
        - --api
        - --logLevel=INFO
        - --configfile=/config/traefik.toml
        resources:
          limits:
            memory: "60Mi"
            cpu: "200m"
          requests:
            memory: "60Mi"
            cpu: "200m"
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /ping
            port: 8082
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /config
          name: config
      volumes:
      - configMap:
          name: traefik-admin-conf
        name: config
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: traefik-admin-ingress-controller-hpa
  namespace: kube-system
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: traefik-admin-ingress-controller
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
