apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-public-deploy
  namespace: consumers
  labels:
    app: app-public-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-public-deploy
  template:
    metadata:
      labels:
        app: app-public-deploy
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '8080'
        prometheus.io/normalizer: 'true'
    spec:
      containers:
      - name: app
        image: eu.gcr.io/slavayssiere-sandbox/app-public:0.0.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: TOPIC_NAME 
          value: "projects/slavayssiere-sandbox/topics/messages-public"
        - name: SECRET_PATH
          value: "/secret/sa-sse.json"
        - name: ZIPKIN_ENDPOINT
          value: "http://jaeger-collector.istio-system.svc.cluster.local:14268/api/traces"
        resources:
          requests:
            memory: 20M
            cpu: 10m
          limits:
            memory: 20M
            cpu: 10m
        volumeMounts:
          - name: secret-sa
            mountPath: "/secret"
            readOnly: true
      terminationGracePeriodSeconds: 15
      volumes:
      - name: secret-sa
        secret:
          secretName: sa-sse
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: app-public-hpa
  namespace: consumers
spec:
  minReplicas: 2
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-public-deploy
  targetCPUUtilizationPercentage: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-public-svc
  namespace: consumers
  labels:
    k8s-app: app-public-svc
spec:
  selector:
    app: app-public-deploy
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: app-public-virtualservice
  namespace: consumers
spec:
  hosts:
  - "public.gcp-wescale.slavayssiere.fr"
  gateways:
  - consumers-gateway-public
  http:
  - route:
    - destination:
        host: app-public-svc
