apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-bigtable-deploy
  namespace: consumers
  labels:
    app: consumer-bigtable-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-bigtable-deploy
  template:
    metadata:
      labels:
        app: consumer-bigtable-deploy
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '8080'
        prometheus.io/normalizer: 'true'
    spec:
      containers:
      - name: my-bt
        image: eu.gcr.io/slavayssiere-sandbox/consumer-bigtable:0.0.15
        imagePullPolicy: IfNotPresent
        env:
        - name: SUB_NAME 
          value: "projects/slavayssiere-sandbox/subscriptions/messages-normalized-sub-bigtable"
        - name: SECRET_PATH
          value: "/secret/sa-pubsub-bigtable.json"
        - name: PROJECT_ID
          value: "slavayssiere-sandbox"
        - name: TABLE_ID
          value: "test-table"
        - name: INSTANCE_ID
          value: "test-instance"
        - name: SUB_AGGREGA 
          value: "projects/slavayssiere-sandbox/subscriptions/aggregator-queue-sub-dataset"
        - name: ZIPKIN_ENDPOINT
          value: "http://jaeger-collector.istio-system.svc.cluster.local:14268/api/traces"
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            memory: 50M
            cpu: 50m
          limits:
            memory: 100M
            cpu: 100m
        volumeMounts:
          - name: secret-sa
            mountPath: "/secret"
            readOnly: true
      terminationGracePeriodSeconds: 15
      volumes:
      - name: secret-sa
        secret:
          secretName: sa-pubsub-bigtable
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: consumer-bigtable-name
  namespace: consumers
spec:
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - external:
      metricName: pubsub.googleapis.com|subscription|num_undelivered_messages
      metricSelector:
        matchLabels:
          resource.labels.subscription_id: "messages-normalized-sub-bigtable"
      targetAverageValue: "10"
    type: External
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: consumer-bigtable-deploy
