apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: injectors
---
## we have to allow:
## 
##    - api.twitter.com
##    - stream.twitter.com
##    - gnip-stream.twitter.com
##
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: twitter-egress
spec:
  hosts:
  - api.twitter.com
  - stream.twitter.com
  - gnip-stream.twitter.com
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  - number: 80
    name: http
    protocol: HTTP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: twitter-egress-vs
spec:
  hosts:
  - api.twitter.com
  - stream.twitter.com
  - gnip-stream.twitter.com
  tls:
  - match:
    - port: 443
      sni_hosts:
      - api.twitter.com
    route:
    - destination:
        host: api.twitter.com
  - match:
    - port: 443
      sni_hosts:
      - stream.twitter.com
    route:
    - destination:
        host: stream.twitter.com
  - match:
    - port: 443
      sni_hosts:
      - gnip-stream.twitter.com
    route:
    - destination:
        host: gnip-stream.twitter.com
