apiVersion: apps/v1
kind: Deployment
metadata:
  name: normalized-twitter-deploy
  namespace: normalizers
  labels:
    app: normalized-twitter-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: normalized-twitter-deploy
  template:
    metadata:
      labels:
        app: normalized-twitter-deploy
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '8080'
        prometheus.io/normalizer: 'true'
    spec:
      containers:
      - name: my-normalized
        image: eu.gcr.io/slavayssiere-sandbox/twitter-normalizer:0.0.2
        imagePullPolicy: Always
        env:
        - name: SUB_NAME 
          value: "projects/slavayssiere-sandbox/subscriptions/twitter-raw-sub"
        - name: TOPIC_NAME 
          value: "projects/slavayssiere-sandbox/topics/twitter-normalized"
        - name: SECRET_PATH
          value: "/secret/sa-pubsub-full.json"
        resources:
          requests:
            memory: 20M
            cpu: 10m
          limits:
            memory: 20M
            cpu: 10m
        volumeMounts:
          - name: secret-sa
            mountPath: "/secret"
            readOnly: true
      terminationGracePeriodSeconds: 15
      volumes:
      - name: secret-sa
        secret:
          secretName: sa-pubsub-full
# ---
# apiVersion: autoscaling/v2beta1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: normalized-hpa-name
# spec:
#   minReplicas: 10
#   maxReplicas: 3000
#   metrics:
#   - external:
#       metricName: pubsub.googleapis.com|subscription|num_undelivered_messages
#       metricSelector:
#         matchLabels:
#           resource.labels.subscription_id: SUB_SHORT_NAME_TPL
#       targetAverageValue: "100"
#     type: External
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: normalized-twitter-deploy
