apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
  labels:
    app: consumer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-deployment
  template:
    metadata:
      labels:
        app: consumer-deployment
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '8080'
        prometheus.io/consumer: 'true'
    spec:
      containers:
      - name: my-consumer
        image: eu.gcr.io/cool-wharf-207907/kaiko-consumer:0.0.6
        imagePullPolicy: Always
        env:
        - name: SUB_NAME 
          value: "projects/cool-wharf-207907/subscriptions/normalized_subcription"
        resources:
          requests:
            memory: 20M
            cpu: 10m
          limits:
            memory: 20M
            cpu: 10m
        volumeMounts:
          - name: secret-sa
            mountPath: "/secret"
            readOnly: true
      volumes:
      - name: secret-sa
        secret:
          secretName: sa-gcp-pubsub
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: consumer-pubsub-hpa
spec:
  minReplicas: 200
  maxReplicas: 5000
  metrics:
  - external:
      metricName: pubsub.googleapis.com|subscription|num_undelivered_messages
      metricSelector:
        matchLabels:
          resource.labels.subscription_id: normalized_subcription
      targetAverageValue: "10"
    type: External
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: consumer-deployment
---

