apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "ingressgateway"
  namespace: istio-system
spec:
  targets:
  - name: istio-ingressgateway
  origins:
  - jwt:
      issuer: "https://cloud.google.com/iap"
      jwksUri: "https://www.gstatic.com/iap/verify/public_key-jwk"
      audiences: 
      - "/projects/500721978414/global/backendServices/4495243212344736592"
      jwt_headers: 
      - "x-goog-iap-jwt-assertion"
  principalBinding: USE_ORIGIN
