apiVersion: apps/v1
kind: Deployment
metadata:
  name: normalized-deployment
  labels:
    app: normalized-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: normalized-deployment
  template:
    metadata:
      labels:
        app: normalized-deployment
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '8080'
    spec:
      containers:
      - name: my-normalized
        image: eu.gcr.io/cool-wharf-207907/kaiko-normalized:0.0.5
        imagePullPolicy: Always
        env:
        - name: SUB_NAME 
          value: "projects/cool-wharf-207907/subscriptions/trade_subcription"
        - name: TOPIC_NAME 
          value: "projects/cool-wharf-207907/topics/normalized_topic"
        resources:
          requests:
            memory: 100M
        volumeMounts:
          - name: secret-sa
            mountPath: "/secret"
            readOnly: true
      volumes:
      - name: secret-sa
        secret:
          secretName: sa-gcp-pubsub
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: normalized-pubsub-hpa
spec:
  minReplicas: 1
  maxReplicas: 100
  metrics:
  - external:
      metricName: pubsub.googleapis.com|subscription|num_undelivered_messages
      metricSelector:
        matchLabels:
          resource.labels.subscription_id: trade_subcription
      targetAverageValue: "10"
    type: External
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: normalized-deployment
