{
 "title": "PlateformPOCWeSCale",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Messages injected (per min)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(messages_injected[1m]))"
    }
   ]
  },
  {
   "title": "Total injected",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(messages_injected[1m]))"
    }
   ]
  },
  {
   "title": "Mean in injector (in ms)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum((rate(mean_in_injector_sum[1m]) / rate(mean_in_injector_count[1m])) / 1000000) / count(mean_in_injector_count)"
    }
   ]
  },
  {
   "title": "Mean latency",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum((rate(mean_in_injector_sum[1m]) / rate(mean_in_injector_count[1m])) / 1000000) / count(mean_in_injector_count)"
    }
   ]
  },
  {
   "title": "Trade1 - message counter per seconds",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(messages_injected{trade=\"projects/cool-wharf-207907/topics/trade1_topic\"}[1m]))"
    }
   ]
  },
  {
   "title": "Trade 1 - Mean publish time (ms)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(mean_in_injector_sum{trade=\"projects/cool-wharf-207907/topics/trade1_topic\"}[1m]) / rate(mean_in_injector_count{trade=\"projects/cool-wharf-207907/topics/trade1_topic\"}[1m]))/1000000"
    }
   ]
  },
  {
   "title": "Trade 2 - message counter per seconds",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(messages_injected{trade=\"projects/cool-wharf-207907/topics/trade2_topic\"}[1m]))"
    }
   ]
  },
  {
   "title": "Trade 2 - Mean publish time (ms)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(mean_in_injector_sum{trade=\"projects/cool-wharf-207907/topics/trade2_topic\"}[1m]) / rate(mean_in_injector_count{trade=\"projects/cool-wharf-207907/topics/trade2_topic\"}[1m]))/1000000"
    }
   ]
  },
  {
   "title": "Trade 3 - message counter per seconds",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(messages_injected{trade=\"projects/cool-wharf-207907/topics/trade3_topic\"}[1m]))"
    }
   ]
  },
  {
   "title": "Trade 3 - Mean publish time (ms)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(mean_in_injector_sum{trade=\"projects/cool-wharf-207907/topics/trade3_topic\"}[1m]) / rate(mean_in_injector_count{trade=\"projects/cool-wharf-207907/topics/trade3_topic\"}[1m])) / 1000000"
    }
   ]
  },
  {
   "title": "Trade 4 - message counter per seconds",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(messages_injected{trade=\"projects/cool-wharf-207907/topics/trade4_topic\"}[1m]))"
    }
   ]
  },
  {
   "title": "Trade 4 - Mean publish time (ms)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(mean_in_injector_sum{trade=\"projects/cool-wharf-207907/topics/trade4_topic\"}[1m]) / rate(mean_in_injector_count{trade=\"projects/cool-wharf-207907/topics/trade4_topic\"}[1m])) / 1000000"
    }
   ]
  },
  {
   "title": "Trade 5 - message counter per seconds",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(messages_injected{trade=\"projects/cool-wharf-207907/topics/trade5_topic\"}[1m]))"
    }
   ]
  },
  {
   "title": "Trade 5 - Mean publish time (ms)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(mean_in_injector_sum{trade=\"projects/cool-wharf-207907/topics/trade5_topic\"}[1m]) / rate(mean_in_injector_count{trade=\"projects/cool-wharf-207907/topics/trade5_topic\"}[1m])) / 1000000"
    }
   ]
  }
 ]
}
{
 "title": "BigTable Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Mean time elapsed (en s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(time_in_bigtable_sum[1m]) / rate(time_in_bigtable_count[1m])) / count(time_in_bigtable_count)) / 1000000000"
    }
   ]
  },
  {
   "title": "Mean time (en s)",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(rate(time_in_bigtable_sum[1m]) / rate(time_in_bigtable_count[1m])) / count(time_in_bigtable_count)) / 1000000000"
    }
   ]
  },
  {
   "title": "Max time elapsed (en s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rate(time_in_bigtable_sum[1m]) / rate(time_in_bigtable_count[1m])) / 1000000000"
    }
   ]
  },
  {
   "title": "Min time elapsed (en s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(rate(time_in_bigtable_sum[1m]) / rate(time_in_bigtable_count[1m])) / 1000000000"
    }
   ]
  }
 ]
}